# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1116, 61)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 23))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actiongray = QtWidgets.QAction(MainWindow)
        self.actiongray.setObjectName("actiongray")
        self.actionsegment = QtWidgets.QAction(MainWindow)
        self.actionsegment.setObjectName("actionsegment")
        self.actiondaoru = QtWidgets.QAction(MainWindow)
        self.actiondaoru.setText("")
        self.actiondaoru.setObjectName("actiondaoru")
        self.actionopenFlu = QtWidgets.QAction(MainWindow)
        self.actionopenFlu.setObjectName("actionopenFlu")
        self.menu_1.addAction(self.actionopen)
        self.menu_1.addAction(self.actionopenFlu)
        self.menu_1.addAction(self.actionsave)
        self.menu.addAction(self.actionsegment)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "荧光强度计算程序"))
        self.menu_1.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "操作"))
        self.actionsave.setText(_translate("MainWindow", "保存结果"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionopen.setText(_translate("MainWindow", "导入细胞图像"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actiongray.setText(_translate("MainWindow", "灰度化"))
        self.actionsegment.setText(_translate("MainWindow", "运行"))
        self.actionopenFlu.setText(_translate("MainWindow", "导入荧光分布"))
