# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_picwin(object):
    def setupUi(self, picwin):
        picwin.setObjectName("picwin")
        self.label = QtWidgets.QLabel(picwin)
        self.label.setGeometry(QtCore.QRect(0, 0, 281, 231))
        self.label.setObjectName("label")

        self.retranslateUi(picwin)
        QtCore.QMetaObject.connectSlotsByName(picwin)

    def retranslateUi(self, picwin):
        _translate = QtCore.QCoreApplication.translate
        picwin.setWindowTitle(_translate("picwin", "picwin"))
        self.label.setText(_translate("picwin", "TextLabel"))
